### ISSUE TITLE
Merging changes from existing forks

### ISSUE THREAD

**Issue by karimbahgat** [pytroll/aggdraw#36]
As you know there are a few forks out there which have made several independent changes and improvements. In my own fork, I have gone through the existing forks and merged a few of the ones that seemed more important, including some bug fixes, freetype things, and added support for line caps and joins (looks like the original author of this has already suggested this #3). The full list of changes that I considered can be seen here: 

https://github.com/karimbahgat/aggdraw/commits/master

More generally it may be worth doing a systematic round of the various forks to see which preexisting changes may be worth incorporating: 

https://github.com/search?p=1&q=aggdraw&type=Repositories
https://github.com/pytroll/aggdraw/network/members

**Comment by karimbahgat** [comment]
This may also include some fixes related to 64-bit support, which I think will be increasingly important as 64-bit systems become more and more common in the future.

**Comment by djhoese** [comment]
Your last comment makes it sound like you work on a 32-bit system. What work do you do involving aggdraw that uses 32-bit instead of 64-bit? In my experience 32-bit systems are usually left for embedded systems, but obviously I don't deal with that much anymore.

As for merging work done by other forks, this is what I did when I first took over the project. This repository was started from @jakul's repository iirc, who had done some of this too. I know that I included as many bug fixes as I could find but I may have only looked at other forks, not similarly named repositories. I know I included python 3 support, some changes for finding freetype, and other bug fixes. Since then I've modified the freetype stuff a lot, fixed various things about the python 3 support including proper handling of unicode, a real version string, and better color string handling.

Looking again now it looks like @scottopell may have some fixes for 64-bit support but AFAIK these haven't been an issue for conda-forge or any current users.

**Comment by karimbahgat** [comment]
For the 64-bit comment, I may have misspoke. I meant to say Python installations that are 32-bit. From the Python downloads options you can always choose 32 or 64 bit, and I remember hearing many people are still sticking to Python 32-bit (even though their computers support 64-bit), since there has been a software lag of popular Python packages that have yet to support 64-bit. I myself still use 32-bit for this reason actually. This is probably mostly due to inertia from a decision I made long ago, and it could be that it should be safe to switch to Python 64-bit now. My impression was that the original version of aggdraw contained an important bug relating to 64-bit Python, and that I had seen someone provide a bugfix for this. 

At any rate, from your comments about the forks, it seems like you have already incorporated most of the same ones, probably including the 64-bit support I think. Maybe rather than chasing this rabbit, let's assume aggdraw on Python 64-bit works fine and instead deal with it if it pops up in the future. 

Given all this, I'm not sure if there's much of a point keeping this issue, so feel free to close it.

**Comment by djhoese** [comment]
> since there has been a software lag of popular Python packages that have yet to support 64-bit

I'm very curious what crowds are having trouble with 64-bit support in python over the last 5 years (at least). You make it sound like *most* and not *some* people are using 32-bit versions of software and python. Besides people who have enterprise/third-party industry software that hasn't been updated to 64-bit support, I think most people are on 64-bit. Maybe I'm spoiled coming from the scientific community, but we have our own types of software lag (old fortran to new fortran or "better" language). Anyway, if aggdraw is something that 32-bit software developers need I'd love to hear from them. Right now 32-bit and 64-bit should be fully supported. If there is a difficulty in supporting both in the future and no one has the time to keep support then 32-bit may be dropped. We'll cross that bridge when we come to it.
