### ISSUE TITLE
Add support to release linux aarch64 wheels

### ISSUE THREAD

**Issue by odidev** [pytroll/aggdraw#79]
Problem
---------
On aarch64, ‘pip install aggdraw’ builds the wheels from source code and then installs it. It requires the user to have a development environment installed on his system. Also, it takes some time to build the wheels than downloading and extracting the wheels from pypi. 

Resolution
-----------
On aarch64, ‘pip install aggdraw’ should download the wheels from pypi

@djhoese and Team Please let me know your interest in releasing aarch64 wheels. I can help in this. To start with could you please tell the steps/CI which you are using presently to release the wheel on pypi.

**Comment by djhoese** [comment]
I am not against it, but not sure how to accomplish it. This project still uses Travis CI and should really be moved to github actions for all of its work. We could base this configuration on what the `pytroll/pyresample` project uses since it also has C compiling as part of its build process.

I won't have time to do this any time soon probably so if you @odidev or someone else has time, please let me know.

**Comment by odidev** [comment]
@djhoese I have moved the CI to Github actions. Could you please review the [PR](https://github.com/pytroll/aggdraw/pull/81)

**Comment by djhoese** [comment]
This is closed as part of your #81. Thanks again.
