### ISSUE TITLE
Diferences between pip version and source-compiled version

### ISSUE THREAD

**Issue by dealfonso** [pytroll/aggdraw#85]
Hi,

I am having an API difference between the version installed using pip and the version installed by hand. I found that if I install `aggdraw` using `pip install aggdraw`, I have the next issue:

```python
Traceback (most recent call last):
(...) 
  File "/opt/canvashanddraw/drawhelper.py", line 134, in _draw_points
    pen = aggdraw.Pen(color, ((1.0 - float(smoothWidth)) * float(actualLineWidth)) + (float(self._options.lineWidth) * float(smoothWidth)), linecap = 2, linejoin = 2)
TypeError: Pen() takes at most 3 arguments (4 given)
```

The help for the class using `help(aggdraw.Pen)` on this version:

```
Help on built-in function Pen in module aggdraw:

Pen(...)
    Creates a Pen object.

    Parameters
    ----------
    color : tuple or str or int
        Pen color. This can be a color tuple (R, G, B) or (R, G, B, A),
        a CSS-style color name, or a color integer (0xaarrggbb).
    width : int, optional
        Pen width. Default 1.
    opacity : int, optional
        Pen opacity. Default 255.
```

But if I follow the process for installing it from source:

```console
$ git clone https://github.com/pytroll/aggdraw
$ cd aggdraw
$ python setup.py build_ext -i
$ python setup.py install
```

The code works as expected, according to the [docs](https://aggdraw.readthedocs.io/en/latest/)

The help for the class using `help(aggdraw.Pen)`:

```
Help on built-in function Pen in module aggdraw:

Pen(...)
    Creates a Pen object.

    Parameters
    ----------
    color : tuple or str or int
        Pen color. This can be a color tuple (R, G, B) or (R, G, B, A),
        a CSS-style color name, or a color integer (0xaarrggbb).
    width : int, optional
        Pen width. Default 1.
    opacity : int, optional
        Pen opacity. Default 255.
    linejoin : int, optional
        Type of line_join. Types are 0=miter_join
        1=miter_join_revert; 2=round_join; 3=bevel_join;
        4=miter_join_round. Default 0 (miter join).
    linecap : int, optional
        Type of linecap. Types are 0=butt_cap;
        1=square_cap; 2=round_cap. Default 1 (butt cap).
    miterlimit : float, optional
        Type of miterlimit. Default 4.0.
```

**Comment by djhoese** [comment]
This is unfortunate. So the `main` branch currently contains an unreleased version of aggdraw that has had a lot of changes made to it including the additional options to the Pen class (linejoin, linecap, miterlimit). The branch that has the latest release in it is currently `maint/1.3`. If you change your install to use that branch or do `pip install git+https://github.com/pytroll/aggdraw.git@maint/1.3` then your execution should be consistent between source install and pip install. To get the matching documentation, try using the "stable" version here:

https://aggdraw.readthedocs.io/en/stable/

I will change the default so "stable" is shown instead of "latest" from now on.

Let me know if you have any other questions.

If you're wondering why `main` has not been released yet it is because the new version of the C++ agg library that it depends on does not produce the same results as the old version and I have not had time to track down why that is. My guess is that most people would be very upset with a version update changing all their output so I have not released it yet. Any help with this would be greatly appreciated.

**Comment by dealfonso** [comment]
Thank you for your quick and detailed response. For sure, you have the responsibility of releasing packages, but I think that if this library is a link to use another library, the results depend on the target library, not on your library. The final results have to do with the target library, not with your library :) 

So I find it appropriate to release the new version, provided it changes the main version. Those needing the specific version obtained by the target library version may stick your library to such a version when releasing their packages.

Thank you for your effort on bringing this library to us.

**Comment by djhoese** [comment]
>  but I think that if this library is a link to use another library, the results depend on the target library, not on your library

Good point...except my own projects show differences that I'm not happy with so I also don't want to deal with the annoyance of what I would consider a "broken" release. I really just need to spend a day walking through the library and understanding the AGG algorithms to figure out what settings/defaults need to be established to reproduce the old behavior.

**Comment by dealfonso** [comment]
thank you again for your effort. I will keep an eye on your project so that I can update mine when you modify it. Just for your records, you can check my project at https://github.com/dealfonso/pycanvashanddraw
