### ISSUE TITLE
Can implicit fallthroughs be made explicit?

### ISSUE THREAD

**Issue by r-barnes** [pytroll/aggdraw#97]
Compiling the code with clang's `-Wimplicit-fallthrough` reveals ~5 cases where fallthroughs are not explicitly marked ([example](https://github.com/pytroll/aggdraw/blob/9f29836b70131a21170585a43d227efdcca5c5cb/agg/include/agg_conv_adaptor_vcgen.h#L102)). Are these bugs where `break` should have been used or are they intentional? If they are intentional, can they be marked with `[[fallthrough]]`?

**Comment by djhoese** [comment]
My guess is a lot of the code identified is from the upstream agg C++ library. We (aggdraw) simply vendor this code in our repository, but are not the creators or even maintainers of that code. I would recommend finding the upstream project and seeing if these cases have been changed since the version we're using here.

As far as cleaning things up in this repository, I'd prefer to limit modifications to the agg C++ library for the reasons I mentioned above and that it makes it harder to update the library in the future.

**Comment by djhoese** [comment]
I think the official project is on sourceforge although not very active. That github repository is likely not the official repository of the project.

**Comment by djhoese** [comment]
I'm going to close this for now. I have added a `patches/` directory in the `maint/1.3` branch if you wanted to make a PR to address these you could put fixes there, but I think I would prefer that we don't change them. This isn't something *we*/aggdraw should be fixing and any fix for them could cause unexpected consequences/differences with the upstream library and make it harder to transition to new versions in the future.
